config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :technicians

  resources :company_infos

  resources :emergency_contacts

  resources :work_orders

  resources :addresses

  resources :drivers_licesnses

  resources :work_order_details

  resources :time_slots

  resources :work_order_statuses

  resources :vehicle_infos

  resources :work_order_times

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :company_info
  belongs_to :emergency_contact
  belongs_to :work_order
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/change_log.rb
class ChangeLog < ActiveRecord::Base
  belongs_to :user
end

app/models/company_info.rb
class CompanyInfo < ActiveRecord::Base
  has_many :technicians
  has_one :address
end

app/models/drivers_licesnse.rb
class DriversLicesnse < ActiveRecord::Base
  belongs_to :technician
end

app/models/emergency_contact.rb
class EmergencyContact < ActiveRecord::Base
  has_one :address
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  belongs_to :company_info
  has_one :company_info
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  belongs_to :work_order
end

app/models/time_slots.rb
class TimeSlots < ActiveRecord::Base
  belongs_to :work_order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/vehicle_info.rb
class VehicleInfo < ActiveRecord::Base
  belongs_to :company_info
end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :technician
  has_one :address
end

app/models/work_order_detail.rb
class WorkOrderDetail < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_details.rb
class WorkOrderDetails < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_status.rb
class WorkOrderStatus < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_time.rb
class WorkOrderTime < ActiveRecord::Base
  belongs_to :work_order
end

app/controllers/vehicle_infos_controller.rb
class VehicleInfosController < ApplicationController
  before_action :set_vehicle_info, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_infos
  # GET /vehicle_infos.json
  def index
    @vehicle_infos = VehicleInfo.all
  end

  # GET /vehicle_infos/1
  # GET /vehicle_infos/1.json
  def show
  end

  # GET /vehicle_infos/new
  def new
    @vehicle_info = VehicleInfo.new
  end

  # GET /vehicle_infos/1/edit
  def edit
  end

  # POST /vehicle_infos
  # POST /vehicle_infos.json
  def create
    @vehicle_info = VehicleInfo.new(vehicle_info_params)

    respond_to do |format|
      if @vehicle_info.save
        format.html { redirect_to @vehicle_info, notice: 'Vehicle info was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_info }
      else
        format.html { render :new }
        format.json { render json: @vehicle_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_infos/1
  # PATCH/PUT /vehicle_infos/1.json
  def update
    respond_to do |format|
      if @vehicle_info.update(vehicle_info_params)
        format.html { redirect_to @vehicle_info, notice: 'Vehicle info was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_info }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_infos/1
  # DELETE /vehicle_infos/1.json
  def destroy
    @vehicle_info.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_infos_url, notice: 'Vehicle info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_info
      @vehicle_info = VehicleInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_info_params
      params.require(:vehicle_info).permit(:year, :make, :model, :registration_state, :color, :plate, :registration_id, :registration_expiration, :insurance_company, :insurance_company, :company_info_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/vehicle_infos_helper.rb
module VehicleInfosHelper
end

app/views/vehicle_infos/_form.html.erb
<%= simple_form_for(@vehicle_info) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :year %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :registration_state %>
    <%= f.input :color %>
    <%= f.input :plate %>
    <%= f.input :registration_id %>
    <%= f.input :registration_expiration %>
    <%= f.input :insurance_company %>
    <%= f.input :insurance_company %>
    <%= f.association :company_info %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehicle_infos/edit.html.erb
<h1>Editing vehicle_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle_info %> |
<%= link_to 'Back', vehicle_infos_path %>

app/views/vehicle_infos/index.html.erb
<h1>Listing vehicle_infos</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>Registration state</th>
      <th>Color</th>
      <th>Plate</th>
      <th>Registration</th>
      <th>Registration expiration</th>
      <th>Insurance company</th>
      <th>Insurance company</th>
      <th>Company info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_infos.each do |vehicle_info| %>
      <tr>
        <td><%= vehicle_info.year %></td>
        <td><%= vehicle_info.make %></td>
        <td><%= vehicle_info.model %></td>
        <td><%= vehicle_info.registration_state %></td>
        <td><%= vehicle_info.color %></td>
        <td><%= vehicle_info.plate %></td>
        <td><%= vehicle_info.registration_id %></td>
        <td><%= vehicle_info.registration_expiration %></td>
        <td><%= vehicle_info.insurance_company %></td>
        <td><%= vehicle_info.insurance_company %></td>
        <td><%= vehicle_info.company_info %></td>
        <td><%= link_to 'Show', vehicle_info %></td>
        <td><%= link_to 'Edit', edit_vehicle_info_path(vehicle_info) %></td>
        <td><%= link_to 'Destroy', vehicle_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle info', new_vehicle_info_path %>

app/views/vehicle_infos/new.html.erb
<h1>New vehicle_info</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicle_infos_path %>

app/views/vehicle_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @vehicle_info.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @vehicle_info.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle_info.model %>
</p>

<p>
  <strong>Registration state:</strong>
  <%= @vehicle_info.registration_state %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle_info.color %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @vehicle_info.plate %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @vehicle_info.registration_id %>
</p>

<p>
  <strong>Registration expiration:</strong>
  <%= @vehicle_info.registration_expiration %>
</p>

<p>
  <strong>Insurance company:</strong>
  <%= @vehicle_info.insurance_company %>
</p>

<p>
  <strong>Insurance company:</strong>
  <%= @vehicle_info.insurance_company %>
</p>

<p>
  <strong>Company info:</strong>
  <%= @vehicle_info.company_info %>
</p>

<%= link_to 'Edit', edit_vehicle_info_path(@vehicle_info) %> |
<%= link_to 'Back', vehicle_infos_path %>