config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :technicians

  resources :company_infos

  resources :emergency_contacts

  resources :work_orders

  resources :addresses

  resources :drivers_licesnses

  resources :work_order_details

  resources :time_slots

  resources :work_order_statuses

  resources :vehicle_infos

  resources :work_order_times

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :company_info
  belongs_to :emergency_contact
  belongs_to :work_order
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/change_log.rb
class ChangeLog < ActiveRecord::Base
  belongs_to :user
end

app/models/company_info.rb
class CompanyInfo < ActiveRecord::Base
  has_many :technicians
  has_one :address
end

app/models/drivers_licesnse.rb
class DriversLicesnse < ActiveRecord::Base
  belongs_to :technician
end

app/models/emergency_contact.rb
class EmergencyContact < ActiveRecord::Base
  has_one :address
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  belongs_to :company_info
  has_one :company_info
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  belongs_to :work_order
end

app/models/time_slots.rb
class TimeSlots < ActiveRecord::Base
  belongs_to :work_order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/vehicle_info.rb
class VehicleInfo < ActiveRecord::Base
  belongs_to :company_info
end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :technician
  has_one :address
end

app/models/work_order_detail.rb
class WorkOrderDetail < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_details.rb
class WorkOrderDetails < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_status.rb
class WorkOrderStatus < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_time.rb
class WorkOrderTime < ActiveRecord::Base
  belongs_to :work_order
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:code, :description, :work_order_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_infos_helper.rb
module CompanyInfosHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/time_slots/_form.html.erb
<%= simple_form_for(@time_slot) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :description %>
    <%= f.association :work_order %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing time_slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<h1>Listing time_slots</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Work order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.code %></td>
        <td><%= time_slot.description %></td>
        <td><%= time_slot.work_order %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time slot', new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New time_slot</h1>

<%= render 'form' %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @time_slot.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @time_slot.description %>
</p>

<p>
  <strong>Work order:</strong>
  <%= @time_slot.work_order %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>