config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :technicians

  resources :company_infos

  resources :emergency_contacts

  resources :work_orders

  resources :addresses

  resources :drivers_licesnses

  resources :work_order_details

  resources :time_slots

  resources :work_order_statuses

  resources :vehicle_infos

  resources :work_order_times

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :company_info
  belongs_to :emergency_contact
  belongs_to :work_order
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/change_log.rb
class ChangeLog < ActiveRecord::Base
  belongs_to :user
end

app/models/company_info.rb
class CompanyInfo < ActiveRecord::Base
  has_many :technicians
  has_one :address
end

app/models/drivers_licesnse.rb
class DriversLicesnse < ActiveRecord::Base
  belongs_to :technician
end

app/models/emergency_contact.rb
class EmergencyContact < ActiveRecord::Base
  has_one :address
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  belongs_to :company_info
  has_one :company_info
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  belongs_to :work_order
end

app/models/time_slots.rb
class TimeSlots < ActiveRecord::Base
  belongs_to :work_order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/vehicle_info.rb
class VehicleInfo < ActiveRecord::Base
  belongs_to :company_info
end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :technician
  has_one :address
end

app/models/work_order_detail.rb
class WorkOrderDetail < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_details.rb
class WorkOrderDetails < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_status.rb
class WorkOrderStatus < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_time.rb
class WorkOrderTime < ActiveRecord::Base
  belongs_to :work_order
end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController
  before_action :set_emergency_contact, only: [:show, :edit, :update, :destroy]

  # GET /emergency_contacts
  # GET /emergency_contacts.json
  def index
    @emergency_contacts = EmergencyContact.all
  end

  # GET /emergency_contacts/1
  # GET /emergency_contacts/1.json
  def show
  end

  # GET /emergency_contacts/new
  def new
    @emergency_contact = EmergencyContact.new
  end

  # GET /emergency_contacts/1/edit
  def edit
  end

  # POST /emergency_contacts
  # POST /emergency_contacts.json
  def create
    @emergency_contact = EmergencyContact.new(emergency_contact_params)

    respond_to do |format|
      if @emergency_contact.save
        format.html { redirect_to @emergency_contact, notice: 'Emergency contact was successfully created.' }
        format.json { render :show, status: :created, location: @emergency_contact }
      else
        format.html { render :new }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergency_contacts/1
  # PATCH/PUT /emergency_contacts/1.json
  def update
    respond_to do |format|
      if @emergency_contact.update(emergency_contact_params)
        format.html { redirect_to @emergency_contact, notice: 'Emergency contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergency_contact }
      else
        format.html { render :edit }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergency_contacts/1
  # DELETE /emergency_contacts/1.json
  def destroy
    @emergency_contact.destroy
    respond_to do |format|
      format.html { redirect_to emergency_contacts_url, notice: 'Emergency contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency_contact
      @emergency_contact = EmergencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_contact_params
      params.require(:emergency_contact).permit(:name, :relationship, :phone_number)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/emergency_contacts/_form.html.erb
<%= simple_form_for(@emergency_contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :relationship %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/emergency_contacts/edit.html.erb
<h1>Editing emergency_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @emergency_contact %> |
<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/index.html.erb
<h1>Listing emergency_contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Relationship</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emergency_contacts.each do |emergency_contact| %>
      <tr>
        <td><%= emergency_contact.name %></td>
        <td><%= emergency_contact.relationship %></td>
        <td><%= emergency_contact.phone_number %></td>
        <td><%= link_to 'Show', emergency_contact %></td>
        <td><%= link_to 'Edit', edit_emergency_contact_path(emergency_contact) %></td>
        <td><%= link_to 'Destroy', emergency_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emergency contact', new_emergency_contact_path %>

app/views/emergency_contacts/new.html.erb
<h1>New emergency_contact</h1>

<%= render 'form' %>

<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emergency_contact.name %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @emergency_contact.relationship %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @emergency_contact.phone_number %>
</p>

<%= link_to 'Edit', edit_emergency_contact_path(@emergency_contact) %> |
<%= link_to 'Back', emergency_contacts_path %>