config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :technicians

  resources :company_infos

  resources :emergency_contacts

  resources :work_orders

  resources :addresses

  resources :drivers_licesnses

  resources :work_order_details

  resources :time_slots

  resources :work_order_statuses

  resources :vehicle_infos

  resources :work_order_times

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :company_info
  belongs_to :emergency_contact
  belongs_to :work_order
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/change_log.rb
class ChangeLog < ActiveRecord::Base
  belongs_to :user
end

app/models/company_info.rb
class CompanyInfo < ActiveRecord::Base
  has_many :technicians
  has_one :address
end

app/models/drivers_licesnse.rb
class DriversLicesnse < ActiveRecord::Base
  belongs_to :technician
end

app/models/emergency_contact.rb
class EmergencyContact < ActiveRecord::Base
  has_one :address
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  belongs_to :company_info
  has_one :company_info
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  belongs_to :work_order
end

app/models/time_slots.rb
class TimeSlots < ActiveRecord::Base
  belongs_to :work_order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/vehicle_info.rb
class VehicleInfo < ActiveRecord::Base
  belongs_to :company_info
end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :technician
  has_one :address
end

app/models/work_order_detail.rb
class WorkOrderDetail < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_details.rb
class WorkOrderDetails < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_status.rb
class WorkOrderStatus < ActiveRecord::Base
  belongs_to :work_order
end

app/models/work_order_time.rb
class WorkOrderTime < ActiveRecord::Base
  belongs_to :work_order
end

app/controllers/company_infos_controller.rb
class CompanyInfosController < ApplicationController
  before_action :set_company_info, only: [:show, :edit, :update, :destroy]

  # GET /company_infos
  # GET /company_infos.json
  def index
    @company_infos = CompanyInfo.all
  end

  # GET /company_infos/1
  # GET /company_infos/1.json
  def show
  end

  # GET /company_infos/new
  def new
    @company_info = CompanyInfo.new
  end

  # GET /company_infos/1/edit
  def edit
  end

  # POST /company_infos
  # POST /company_infos.json
  def create
    @company_info = CompanyInfo.new(company_info_params)

    respond_to do |format|
      if @company_info.save
        format.html { redirect_to @company_info, notice: 'Company info was successfully created.' }
        format.json { render :show, status: :created, location: @company_info }
      else
        format.html { render :new }
        format.json { render json: @company_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_infos/1
  # PATCH/PUT /company_infos/1.json
  def update
    respond_to do |format|
      if @company_info.update(company_info_params)
        format.html { redirect_to @company_info, notice: 'Company info was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_info }
      else
        format.html { render :edit }
        format.json { render json: @company_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_infos/1
  # DELETE /company_infos/1.json
  def destroy
    @company_info.destroy
    respond_to do |format|
      format.html { redirect_to company_infos_url, notice: 'Company info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_info
      @company_info = CompanyInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_info_params
      params.require(:company_info).permit(:name, :contract_date, :liability_insurance_date, :liability_insurance_company, :liability_insurance_policy_number, :workers_comp_company, :workers_comp_policy_number, :business_registrataion_expiration, :annual_filing_date)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_infos_helper.rb
module CompanyInfosHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/company_infos/_form.html.erb
<%= simple_form_for(@company_info) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :contract_date %>
    <%= f.input :liability_insurance_date %>
    <%= f.input :liability_insurance_company %>
    <%= f.input :liability_insurance_policy_number %>
    <%= f.input :workers_comp_company %>
    <%= f.input :workers_comp_policy_number %>
    <%= f.input :business_registrataion_expiration %>
    <%= f.input :annual_filing_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/company_infos/edit.html.erb
<h1>Editing company_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_info %> |
<%= link_to 'Back', company_infos_path %>

app/views/company_infos/index.html.erb
<h1>Listing company_infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contract date</th>
      <th>Liability insurance date</th>
      <th>Liability insurance company</th>
      <th>Liability insurance policy number</th>
      <th>Workers comp company</th>
      <th>Workers comp policy number</th>
      <th>Business registrataion expiration</th>
      <th>Annual filing date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_infos.each do |company_info| %>
      <tr>
        <td><%= company_info.name %></td>
        <td><%= company_info.contract_date %></td>
        <td><%= company_info.liability_insurance_date %></td>
        <td><%= company_info.liability_insurance_company %></td>
        <td><%= company_info.liability_insurance_policy_number %></td>
        <td><%= company_info.workers_comp_company %></td>
        <td><%= company_info.workers_comp_policy_number %></td>
        <td><%= company_info.business_registrataion_expiration %></td>
        <td><%= company_info.annual_filing_date %></td>
        <td><%= link_to 'Show', company_info %></td>
        <td><%= link_to 'Edit', edit_company_info_path(company_info) %></td>
        <td><%= link_to 'Destroy', company_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company info', new_company_info_path %>

app/views/company_infos/new.html.erb
<h1>New company_info</h1>

<%= render 'form' %>

<%= link_to 'Back', company_infos_path %>

app/views/company_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_info.name %>
</p>

<p>
  <strong>Contract date:</strong>
  <%= @company_info.contract_date %>
</p>

<p>
  <strong>Liability insurance date:</strong>
  <%= @company_info.liability_insurance_date %>
</p>

<p>
  <strong>Liability insurance company:</strong>
  <%= @company_info.liability_insurance_company %>
</p>

<p>
  <strong>Liability insurance policy number:</strong>
  <%= @company_info.liability_insurance_policy_number %>
</p>

<p>
  <strong>Workers comp company:</strong>
  <%= @company_info.workers_comp_company %>
</p>

<p>
  <strong>Workers comp policy number:</strong>
  <%= @company_info.workers_comp_policy_number %>
</p>

<p>
  <strong>Business registrataion expiration:</strong>
  <%= @company_info.business_registrataion_expiration %>
</p>

<p>
  <strong>Annual filing date:</strong>
  <%= @company_info.annual_filing_date %>
</p>

<%= link_to 'Edit', edit_company_info_path(@company_info) %> |
<%= link_to 'Back', company_infos_path %>